### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by aelligp** [PTsolvers/JustRelax.jl#88]
This issue should be a place to add tasks and mark them as complete.

- [ ] Plastic strain/ strain weakening
- [ ] Thermal stresses [Kiss et al. (2023)](https://doi.org/10.1029/2022JB025341)
- [ ] Marker Chain Freesurface stabilisation 
- [ ] Tensile Plasticity [Kiss et al. (2023)](https://doi.org/10.1029/2022JB025341)

**Comment by albert-de-montserrat** [comment]
The last point should be a GeoParams issue though

**Comment by boriskaus** [comment]
correct, but we should make sure that `JustRelax` uses these `GeoParams` features rather than the status-quo which is hand-coding plasticity

**Comment by albert-de-montserrat** [comment]
Plastic softening already merged in GeoParams in [here](https://github.com/JuliaGeodynamics/GeoParams.jl/pull/152)

**Comment by boriskaus** [comment]
do you currently use the total strain or plastic strain to weaken? Plastic strain would be useful to have as well

**Comment by albert-de-montserrat** [comment]
As for GeoParams, it can be any of them. Im working on the JustRelax
kernels now; I was thinking of using the plastic one.

**Comment by albert-de-montserrat** [comment]
Marker chain addressed by [#43](https://github.com/JuliaGeodynamics/JustPIC.jl/pull/43)

**Comment by aelligp** [comment]
Thermal Stresses are addressed by #115

**Comment by aelligp** [comment]
Add a flag/throw error if the BC's are not set properly e.g.:
```julia
            flow_bcs    = FlowBoundaryConditions(;
                no_slip     = (left=true, right=true, top=true, bot=true),
                free_slip   = (left=true, right=false, top=false, bot=false),
            )```
This should lead to an error or warning as both `no_slip` and `free_slip` on the left boundary is set to true

**Comment by albert-de-montserrat** [comment]
Throwing sounds more appropriate

**Comment by aelligp** [comment]
- [ ] Rate dependent friction (Book of Gerya, 2019)
- [ ] Seismo-thermomechanical: Adaptive timestepping (Book of Gerya, 2019)

**Comment by boriskaus** [comment]
Rate dependent friction should obviously be added to GP
